spring.application.name=PixGuard


spring.datasource.url=jdbc:postgresql://localhost:5432/bd_pix_guard
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
