spring.application.name=AuthenticationBoleto


spring.datasource.url=jdbc:postgresql://localhost:5432/bd_authentication_boleto
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
